name: dmood
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^2.17.0
dependencies: 
  flutter: 
    sdk: flutter
  # flutter_localizations: 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  aws_dynamodb_api: ^2.0.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.6
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - lib/images/
    - .env
