name: dmood
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0" # Ensure compatibility with SDK versions

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # Ensure indentation aligns with flutter_localizations
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  animated_text_kit: ^4.2.1
  aws_dynamodb_api: ^2.0.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.6
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  intl: ^0.18.0
  image_picker: ^1.0.4
  amplify_flutter: ^1.6.0
  amplify_storage_s3: ^1.6.0
  file_picker: ^6.1.1
  amplify_auth_cognito: ^1.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
